spring:
  application:
    name: react-pizza-api
  datasource:
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/react_pizza_db
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true