--liquibase formatted sql

--changeset alex:1

CREATE TABLE pizza
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title text NOT NULL UNIQUE ,
    imageUrl text,
    category_id int REFERENCES category(id) NOT NULL ,
    rating smallint NOT NULL
);