--liquibase formatted sql

--changeset alex:1

CREATE TABLE pizza_item
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    pizza_id int REFERENCES pizza(id) NOT NULL ,
    pizza_type_id int REFERENCES pizza_type(id) NOT NULL ,
    pizza_size_id int REFERENCES pizza_size(id) NOT NULL ,
    price decimal NOT NULL CHECK ( price > 0 )
);